### ISSUE TITLE
Local Push Notification

### ISSUE THREAD

**Issue by juliusbtesh** [parse-server-modules/parse-server-onesignal-push-adapter#31]
Is there a way to send out a push notification based on the user's local timezone??
This function is high priority for an app I am developing and I cannot figure this function out.

**Comment by gdeglin** [comment]
Yes. However to do you should install the OneSignal SDK in your app (which will track the device's timezone and synchronize it with OneSignal), and then use the [OneSignal REST API](https://documentation.onesignal.com/reference) to send notifications instead of using this push adapter.

Closing this for now but feel free to re-open if you have any additional questions.

**Comment by juliusbtesh** [comment]
Wait, is there no way to use this api adapter instead of what you are suggesting? Since all my installations are going straight to Parse's database with all the correct information. It would be a lot easier to continue managing it this way. Parse does have the timezones as well... So maybe there's a way to continue using Parse's installation but send it through the OS REST API??
